netgen_block_manager:
    block_definitions:
        title:
            view_types:
                title:
                    name: 'Title'
                section:
                    name: 'Title (section)'
                section_gray:
                    name: 'Title (section gray)'

        list:
            view_types:
                list:
                    name: 'List'
                    item_view_types: &list_item_view_types
                        standard:
                            name: 'Standard'
                        standard_with_intro:
                            name: 'Standard (with intro)'
                        overlay:
                            name: 'Overlay'
                        line:
                            name: 'Line'
                        mini:
                            name: 'Mini'
                        listitem:
                            name: 'List item'
                        listitem_with_intro:
                            name: 'List item (with intro)'
                list_numbered:
                    name: 'List (numbered)'
                    item_view_types: *list_item_view_types
                grid:
                    name: 'Grid'
                    item_view_types: *list_item_view_types

        gallery:
            view_types:
                slider:
                    name: 'Slider'
                    item_view_types:
                        slide:
                            name: 'Slide'
                thumb_gallery:
                    name: 'Thumb gallery'
                grid_gallery:
                    name: 'Grid gallery'
                sushi_bar:
                    name: 'Sushi bar'
