netgen_block_manager:
    system:
        frontend_group:
            view:
                item_view:
                    default:
                        ezcontent:
                            template: "NetgenMoreDemoBundle:item:ezcontent.html.twig"
                            match:
                                item\value_type: ezcontent
                        ezlocation:
                            template: "NetgenMoreDemoBundle:item:ezlocation.html.twig"
                            match:
                                item\value_type: ezlocation
