parameters:
    ngsite.default.site_domain: localhost
    ngsite.default.locations.site_info.id: 65
    collected_info_sender: info@netgen.io
    collected_info_recipient: test@netgen.io
    server_environment: dev
