ezpublish:
    system:
        frontend_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"
            user:
                login_template: "@ezdesign/user/login.html.twig"

netgen_tags:
    system:
        frontend_group:
            tag_view:
                template: "@ezdesign/tag/view.html.twig"
                related_content_list:
                    limit: 6
                    return_content_info: false

netgen_ez_platform_site_api:
    system:
        frontend_group:
            override_url_alias_view_action: true
