netgen_block_manager:
    system:
        frontend_group:
            view:
                block_view:
                    default:
                        title\section:
                            template: "@NetgenMoreDemo/layouts/block/title/section.html.twig"
                            match:
                                block\definition: title
                                block\view_type: section

                        title\section_gray:
                            template: "@NetgenMoreDemo/layouts/block/title/section_gray.html.twig"
                            match:
                                block\definition: title
                                block\view_type: section_gray

                        list\numbered:
                            template: "@NetgenMoreDemo/layouts/block/list/numbered.html.twig"
                            match:
                                block\definition: list
                                block\view_type: list_numbered

                        list\grid_featured:
                            template: "@NetgenMoreDemo/layouts/block/list/grid_featured.html.twig"
                            match:
                                block\definition: list
                                block\view_type: grid_featured

    view:
        block_view:
            api:
                list\numbered:
                    template: "@NetgenBlockManager/api/block/list/list.html.twig"
                    match:
                        block\definition: list
                        block\view_type: list_numbered

                list\grid_featured:
                    template: "@NetgenBlockManager/api/block/list/grid.html.twig"
                    match:
                        block\definition: list
                        block\view_type: grid_featured
