netgen_block_manager:
    system:
        frontend_group:
            view:
                item_view:
                    default:
                        ezcontent:
                            template: "@ezdesign/layouts/item/ezcontent.html.twig"
                            match:
                                item\value_type: ezcontent
                        ezlocation:
                            template: "@ezdesign/layouts/item/ezlocation.html.twig"
                            match:
                                item\value_type: ezlocation
