parameters:
    ngmore.layouts.block.plugin.background_color.colors:
        yellow: 'block.plugin.background_color.yellow'
        white: 'block.plugin.background_color.white'
        black: 'block.plugin.background_color.black'

services:
