ezpublish:
    system:
        ngmore_frontend_group:
            block_view:
                ContentGrid:
                    template: NetgenMoreDemoBundle:override/block:content_grid.html.twig
                    match:
                        Type: ContentGrid

            location_view:
                full:
                    ng_frontpage:
                        template: NetgenMoreDemoBundle:override/full:ng_frontpage.html.twig
                        match:
                            Identifier\ContentType: ng_frontpage
