snc_redis:
    clients:
        symfony_profiler:
            type: '%profiler_storage_driver%'
            alias: symfony_profiler
            dsn: 'redis://%profiler_storage_dsn%'
            options:
                prefix: '%profiler_storage_namespace%'
