parameters:
    ngmore_legacy.default.ngmore:
        SpecialNodes:
            SiteInfoNode: %ngmore.default.locations.site_info.id%
            SidebarsParentNode: %ngmore.default.locations.sidebars_parent.id%

        GoogleMapsSettings:
            DefaultLatitude: %ngmore.default.google_maps.latitude%
            DefaultLongitude: %ngmore.default.google_maps.longitude%
            DefaultZoom: %ngmore.default.google_maps.zoom%
            DefaultMapType: %ngmore.default.google_maps.map_type%

        SiteSettings:
            GoogleAnalyticsCode: %ngmore.default.site_settings.google_analytics_code%
            GoogleAnalyticsUniversal: %ngmore.default.site_settings.google_analytics_universal%
            AddThisCode: %ngmore.default.site_settings.add_this_code%
            TypeKitCode: %ngmore.default.site_settings.typekit_code%
            SublimeVideoCode: %ngmore.default.site_settings.sublime_video_code%
            FacebookApi: %ngmore.default.site_settings.facebook_api%
