parameters:
    ngmore_legacy.frontend_group.site:
        DatabaseSettings:
            SQLOutput: %ngmore_legacy.frontend_group.database_settings.sql_output%
        ContentSettings:
            ViewCaching: %ngmore_legacy.frontend_group.content_settings.view_caching%
        OverrideSettings:
            Cache: %ngmore_legacy.frontend_group.override_settings.cache%
        TemplateSettings:
            Debug: %ngmore_legacy.frontend_group.template_settings.debug%
            DevelopmentMode: %ngmore_legacy.frontend_group.template_settings.development_mode%
            TemplateCache: %ngmore_legacy.frontend_group.template_settings.template_cache%
            TemplateCompile: %ngmore_legacy.frontend_group.template_settings.template_compile%
            ShowUsedTemplates: %ngmore_legacy.frontend_group.template_settings.show_used_templates%
            ShowXHTMLCode: %ngmore_legacy.frontend_group.template_settings.show_xhtml_code%
        DebugSettings:
            DebugOutput: %ngmore_legacy.frontend_group.debug_settings.debug_output%
            DebugRedirection: %ngmore_legacy.frontend_group.debug_settings.debug_redirection%

    ngmore_legacy.administration_group.site:
        DatabaseSettings:
            SQLOutput: %ngmore_legacy.default.database_settings.sql_output%
        ContentSettings:
            ViewCaching: %ngmore_legacy.default.content_settings.view_caching%
        OverrideSettings:
            Cache: %ngmore_legacy.default.override_settings.cache%
        TemplateSettings:
            Debug: %ngmore_legacy.default.template_settings.debug%
            DevelopmentMode: %ngmore_legacy.default.template_settings.development_mode%
            TemplateCache: %ngmore_legacy.default.template_settings.template_cache%
            TemplateCompile: %ngmore_legacy.default.template_settings.template_compile%
            ShowUsedTemplates: %ngmore_legacy.default.template_settings.show_used_templates%
            ShowXHTMLCode: %ngmore_legacy.default.template_settings.show_xhtml_code%
        DebugSettings:
            DebugOutput: %ngmore_legacy.default.debug_settings.debug_output%
            DebugRedirection: %ngmore_legacy.default.debug_settings.debug_redirection%
