imports:
    - { resource: layouts/blocks.yml }
    - { resource: layouts/block_view.yml }
    - { resource: layouts/item_view.yml }
    - { resource: layouts/services.yml }

parameters:
    # Overriden from site bundle due to typo in narrow identifier
    ngsite.layouts.block.plugin.set_container.sizes:
        '': 'block.plugin.set_container.regular'
        'narrow': 'block.plugin.set_container.narrow'
        'wide': 'block.plugin.set_container.wide'
