parameters:
    netgen_content_browser.ezpublish.default_item_template: '@@NetgenMoreDemo/browser/item.html.twig'
    netgen_content_browser.ezpublish.default_preview_template: '@@NetgenMoreDemo/browser/ngcb_preview.html.twig'
