ezpublish:
    system:
        frontend_group:
            location_view:
                full:
                    ng_frontpage:
                        template: NetgenMoreDemoBundle:content/full:ng_frontpage.html.twig
                        match:
                            Identifier\ContentType: ng_frontpage
                    ng_category:
                        template: NetgenMoreDemoBundle:content/full:ng_category.html.twig
                        controller: ngmore.controller.full_view:viewNgCategoryLocation
                        match:
                            Identifier\ContentType: ng_category
                    ng_category_page:
                        template: NetgenMoreDemoBundle:content/full:ng_category_page.html.twig
                        controller: ngmore.controller.full_view:viewNgCategoryPageLocation
                        match:
                            Identifier\ContentType: ng_category_page
                    ng_landing_page:
                        template: NetgenMoreDemoBundle:content/full:ng_landing_page.html.twig
                        controller: ngmore.controller.full_view:viewNgLandingPageLocation
                        match:
                            Identifier\ContentType: ng_landing_page
                    ng_article:
                        template: NetgenMoreDemoBundle:content/full:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_news:
                        template: NetgenMoreDemoBundle:content/full:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_blog_post:
                        template: NetgenMoreDemoBundle:content/full:ng_blog_post.html.twig
                        match:
                            Identifier\ContentType: ng_blog_post
                    ng_audio:
                        template: NetgenMoreDemoBundle:content/full:ng_audio.html.twig
                        match:
                            Identifier\ContentType: ng_audio
                    ng_gallery:
                        template: NetgenMoreDemoBundle:content/full:ng_gallery.html.twig
                        match:
                            Identifier\ContentType: ng_gallery
                    ng_video:
                        template: NetgenMoreDemoBundle:content/full:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    ng_htmlbox:
                        template: NetgenMoreDemoBundle:content/full:ng_htmlbox.html.twig
                        match:
                            Identifier\ContentType: ng_htmlbox
                line:
                    ng_frontpage:
                        template: NetgenMoreDemoBundle:content/line:ng_frontpage.html.twig
                        match:
                            Identifier\ContentType: ng_frontpage
                    ng_category:
                        template: NetgenMoreDemoBundle:content/line:ng_category.html.twig
                        match:
                            Identifier\ContentType: ng_category
                    ng_category_page:
                        template: NetgenMoreDemoBundle:content/line:ng_category_page.html.twig
                        match:
                            Identifier\ContentType: ng_category_page
                    ng_landing_page:
                        template: NetgenMoreDemoBundle:content/line:ng_landing_page.html.twig
                        match:
                            Identifier\ContentType: ng_landing_page
                    ng_article:
                        template: NetgenMoreDemoBundle:content/line:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_news:
                        template: NetgenMoreDemoBundle:content/line:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_blog_post:
                        template: NetgenMoreDemoBundle:content/line:ng_blog_post.html.twig
                        match:
                            Identifier\ContentType: ng_blog_post
                    ng_audio:
                        template: NetgenMoreDemoBundle:content/line:ng_audio.html.twig
                        match:
                            Identifier\ContentType: ng_audio
                    ng_gallery:
                        template: NetgenMoreDemoBundle:content/line:ng_gallery.html.twig
                        match:
                            Identifier\ContentType: ng_gallery
                    ng_video:
                        template: NetgenMoreDemoBundle:content/line:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    ng_htmlbox:
                        template: NetgenMoreDemoBundle:content/line:ng_htmlbox.html.twig
                        match:
                            Identifier\ContentType: ng_htmlbox
                    ng_feedback_form:
                        template: NetgenMoreDemoBundle:content/line:ng_feedback_form.html.twig
                        match:
                            Identifier\ContentType: ng_feedback_form
                    ng_shortcut:
                        template: NetgenMoreDemoBundle:content/line:ng_shortcut.html.twig
                        match:
                            Identifier\ContentType: ng_shortcut
                    image:
                        template: NetgenMoreDemoBundle:content/line:image.html.twig
                        match:
                            Identifier\ContentType: image
                    file:
                        template: NetgenMoreDemoBundle:content/line:file.html.twig
                        match:
                            Identifier\ContentType: file
                listitem:
                    ng_news:
                        template: NetgenMoreDemoBundle:content/listitem:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_video:
                        template: NetgenMoreDemoBundle:content/listitem:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    ng_shortcut:
                        template: NetgenMoreDemoBundle:content/listitem:ng_shortcut.html.twig
                        match:
                            Identifier\ContentType: ng_shortcut
                    listitem:
                        template: NetgenMoreDemoBundle:content:listitem.html.twig
                        match: ~
                standard:
                    ng_article:
                        template: NetgenMoreDemoBundle:content/standard:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_audio:
                        template: NetgenMoreDemoBundle:content/standard:ng_audio.html.twig
                        match:
                            Identifier\ContentType: ng_audio
                    ng_banner:
                        template: NetgenMoreDemoBundle:content/standard:ng_banner.html.twig
                        match:
                            Identifier\ContentType: ng_banner
                    ng_blog_post:
                        template: NetgenMoreDemoBundle:content/standard:ng_blog_post.html.twig
                        match:
                            Identifier\ContentType: ng_blog_post
                    ng_category:
                        template: NetgenMoreDemoBundle:content/standard:ng_category.html.twig
                        match:
                            Identifier\ContentType: ng_category
                    ng_category_page:
                        template: NetgenMoreDemoBundle:content/standard:ng_category_page.html.twig
                        match:
                            Identifier\ContentType: ng_category_page
                    ng_feedback_form:
                        template: NetgenMoreDemoBundle:content/standard:ng_feedback_form.html.twig
                        match:
                            Identifier\ContentType: ng_feedback_form
                    ng_frontpage:
                        template: NetgenMoreDemoBundle:content/standard:ng_frontpage.html.twig
                        match:
                            Identifier\ContentType: ng_frontpage
                    ng_gallery:
                        template: NetgenMoreDemoBundle:content/standard:ng_gallery.html.twig
                        match:
                            Identifier\ContentType: ng_gallery
                    ng_htmlbox:
                        template: NetgenMoreDemoBundle:content/standard:ng_htmlbox.html.twig
                        match:
                            Identifier\ContentType: ng_htmlbox
                    ng_landing_page:
                        template: NetgenMoreDemoBundle:content/standard:ng_landing_page.html.twig
                        match:
                            Identifier\ContentType: ng_landing_page
                    ng_news:
                        template: NetgenMoreDemoBundle:content/standard:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_shortcut:
                        template: NetgenMoreDemoBundle:content/standard:ng_shortcut.html.twig
                        match:
                            Identifier\ContentType: ng_shortcut
                    ng_video:
                        template: NetgenMoreDemoBundle:content/standard:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    image:
                        template: NetgenMoreDemoBundle:content/standard:image.html.twig
                        match:
                            Identifier\ContentType: image
                    standard:
                        template: NetgenMoreDemoBundle:content:standard.html.twig
                        match: ~
                mini:
                    ng_article:
                        template: NetgenMoreDemoBundle:content/mini:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_news:
                        template: NetgenMoreDemoBundle:content/mini:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_video:
                        template: NetgenMoreDemoBundle:content/mini:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    mini:
                        template: NetgenMoreDemoBundle:content:mini.html.twig
                        match: ~
                overlay:
                    ng_article:
                        template: NetgenMoreDemoBundle:content/overlay:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_news:
                        template: NetgenMoreDemoBundle:content/overlay:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_video:
                        template: NetgenMoreDemoBundle:content/overlay:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    overlay:
                        template: NetgenMoreDemoBundle:content:overlay.html.twig
                        match: ~
                slide:
                    ng_article:
                        template: NetgenMoreDemoBundle:content/slide:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_banner:
                        template: NetgenMoreDemoBundle:content/slide:ng_banner.html.twig
                        match:
                            Identifier\ContentType: ng_banner
                    ng_blog_post:
                        template: NetgenMoreDemoBundle:content/slide:ng_blog_post.html.twig
                        match:
                            Identifier\ContentType: ng_blog_post
                    ng_news:
                        template: NetgenMoreDemoBundle:content/slide:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_video:
                        template: NetgenMoreDemoBundle:content/slide:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    image:
                        template: NetgenMoreDemoBundle:content/slide:image.html.twig
                        match:
                            Identifier\ContentType: image
                    slide:
                        template: NetgenMoreDemoBundle:content:slide.html.twig
                        match: ~
                search:
                    search:
                        template: NetgenMoreDemoBundle:content:search.html.twig
                        match: ~

            content_view:
                embed:
                    ng_frontpage:
                        template: NetgenMoreDemoBundle:content/embed:ng_frontpage.html.twig
                        match:
                            Identifier\ContentType: ng_frontpage
                    ng_category:
                        template: NetgenMoreDemoBundle:content/embed:ng_category.html.twig
                        match:
                            Identifier\ContentType: ng_category
                    ng_category_page:
                        template: NetgenMoreDemoBundle:content/embed:ng_category_page.html.twig
                        match:
                            Identifier\ContentType: ng_category_page
                    ng_landing_page:
                        template: NetgenMoreDemoBundle:content/embed:ng_landing_page.html.twig
                        match:
                            Identifier\ContentType: ng_landing_page
                    ng_article:
                        template: NetgenMoreDemoBundle:content/embed:ng_article.html.twig
                        match:
                            Identifier\ContentType: ng_article
                    ng_news:
                        template: NetgenMoreDemoBundle:content/embed:ng_news.html.twig
                        match:
                            Identifier\ContentType: ng_news
                    ng_blog_post:
                        template: NetgenMoreDemoBundle:content/embed:ng_blog_post.html.twig
                        match:
                            Identifier\ContentType: ng_blog_post
                    ng_audio:
                        template: NetgenMoreDemoBundle:content/embed:ng_audio.html.twig
                        match:
                            Identifier\ContentType: ng_audio
                    ng_gallery:
                        template: NetgenMoreDemoBundle:content/embed:ng_gallery.html.twig
                        match:
                            Identifier\ContentType: ng_gallery
                    ng_video:
                        template: NetgenMoreDemoBundle:content/embed:ng_video.html.twig
                        match:
                            Identifier\ContentType: ng_video
                    ng_htmlbox:
                        template: NetgenMoreDemoBundle:content/embed:ng_htmlbox.html.twig
                        match:
                            Identifier\ContentType: ng_htmlbox
                    ng_feedback_form:
                        template: NetgenMoreDemoBundle:content/embed:ng_feedback_form.html.twig
                        match:
                            Identifier\ContentType: ng_feedback_form
                    ng_shortcut:
                        template: NetgenMoreDemoBundle:content/embed:ng_shortcut.html.twig
                        match:
                            Identifier\ContentType: ng_shortcut
                    ng_banner:
                        template: NetgenMoreDemoBundle:content/embed:ng_banner.html.twig
                        match:
                            Identifier\ContentType: ng_banner
                    image:
                        template: NetgenMoreDemoBundle:content/embed:image.html.twig
                        controller: ngmore.controller.embed_view:embedImageContent
                        match:
                            Identifier\ContentType: image
                    file:
                        template: NetgenMoreDemoBundle:content/embed:file.html.twig
                        match:
                            Identifier\ContentType: file
