ezpublish:
    ezpage:
        layouts:
            1ZonesA:
                name: '1 zone A'
                template: 'NetgenMoreDemoBundle:layouts:1_zones_a.html.twig'
            2ZonesSmart:
                name: '2 zones (smart)'
                template: 'NetgenMoreDemoBundle:layouts:2_zones_smart.html.twig'
            4ZonesA:
                name: '4 zones A'
                template: 'NetgenMoreDemoBundle:layouts:4_zones_a.html.twig'
            4ZonesB:
                name: '4 zones B'
                template: 'NetgenMoreDemoBundle:layouts:4_zones_b.html.twig'
            4ZonesC:
                name: '4 zones C'
                template: 'NetgenMoreDemoBundle:layouts:4_zones_c.html.twig'
            6ZonesA:
                name: '6 zones A'
                template: 'NetgenMoreDemoBundle:layouts:6_zones_a.html.twig'
            NGRegionLayout:
                name: 'Region layout'
                template: ~

        enabledLayouts:
            - 1ZonesA
            - 2ZonesSmart
            - 4ZonesA
            - 4ZonesB
            - 4ZonesC
            - 6ZonesA
            - NGRegionLayout

        blocks:
            PageTitle:
                name: 'Page title'
            ContentGrid:
                name: 'Content grid'
            ContentGridDynamic:
                name: 'Content grid (dynamic)'
            MenuDynamic:
                name: 'Menu (dynamic)'
            TagsCloud:
                name: 'Tags cloud'

        enabledBlocks:
            - PageTitle
            - ContentGrid
            - ContentGridDynamic
            - MenuDynamic
            - TagsCloud
