ezpublish:
    ezpage:
        layouts:
            1ZonesA:
                template: 'NetgenMoreDemoBundle:layouts:1_zones_a.html.twig'
            2ZonesSmart:
                template: 'NetgenMoreDemoBundle:layouts:2_zones_smart.html.twig'
            4ZonesA:
                template: 'NetgenMoreDemoBundle:layouts:4_zones_a.html.twig'
            4ZonesB:
                template: 'NetgenMoreDemoBundle:layouts:4_zones_b.html.twig'
            4ZonesC:
                template: 'NetgenMoreDemoBundle:layouts:4_zones_c.html.twig'
            6ZonesA:
                template: 'NetgenMoreDemoBundle:layouts:6_zones_a.html.twig'
