ezpublish:
    system:
        default:
            ezpage:
                layouts:
                    1ZonesA:
                        template: 'NetgenMoreDemoBundle:zone:1_zones_a.html.twig'
                    2ZonesSmart:
                        template: 'NetgenMoreDemoBundle:zone:2_zones_smart.html.twig'
                    4ZonesA:
                        template: 'NetgenMoreDemoBundle:zone:4_zones_a.html.twig'
                    4ZonesB:
                        template: 'NetgenMoreDemoBundle:zone:4_zones_b.html.twig'
                    4ZonesC:
                        template: 'NetgenMoreDemoBundle:zone:4_zones_c.html.twig'
                    6ZonesA:
                        template: 'NetgenMoreDemoBundle:zone:6_zones_a.html.twig'
