imports:
    - { resource: parameters.yml }
    - { resource: templates.yml }
    - { resource: block_view.yml }
    - { resource: content_view.yml }
    - { resource: ezpage.yml }
    - { resource: image.yml }
    - { resource: opengraph.yml }
    - { resource: legacy.yml }

ezpublish:
    system:
        frontend_group:
            pagelayout: "NetgenMoreDemoBundle::pagelayout.html.twig"
            user:
                login_template: "NetgenMoreDemoBundle:user:login.html.twig"

ez_publish_legacy:
    system:
        frontend_group:
            templating:
                view_layout: "NetgenMoreDemoBundle::pagelayout_legacy.html.twig"
                module_layout: "NetgenMoreDemoBundle::pagelayout_module.html.twig"
