imports:
    - { resource: parameters.yml }
    - { resource: templates.yml }
    - { resource: content_view.yml }
    - { resource: image.yml }
    - { resource: opengraph.yml }
    - { resource: legacy.yml }
    - { resource: info_collection.yml }
    - { resource: layouts.yml }
    - { resource: browser.yml }

ezpublish:
    system:
        frontend_group:
            pagelayout: "NetgenMoreDemoBundle::pagelayout.html.twig"
            user:
                login_template: "NetgenMoreDemoBundle:user:login.html.twig"

ez_publish_legacy:
    system:
        frontend_group:
            templating:
                view_layout: "NetgenMoreDemoBundle::pagelayout_legacy.html.twig"
                module_layout: "NetgenMoreDemoBundle::pagelayout_module.html.twig"

netgen_tags:
    system:
        frontend_group:
            tag_view:
                template: "NetgenMoreDemoBundle:tag:view.html.twig"

netgen_ez_platform_site_api:
    system:
        frontend_group:
            override_url_alias_view_action: true
