imports:
    - { resource: parameters.yml }
    - { resource: override.yml }
    - { resource: ezpage.yml }
    - { resource: image.yml }
    - { resource: opengraph.yml }
    - { resource: legacy.yml }

ezpublish:
    system:
        frontend_group:
            user:
                layout: %ngmore.default.pagelayout%

ez_publish_legacy:
    system:
        frontend_group:
            templating:
                view_layout: 'NetgenMoreDemoBundle::pagelayout_legacy.html.twig'
                module_layout: 'NetgenMoreDemoBundle::pagelayout_module.html.twig'
