imports:
    - { resource: override.yml }
    - { resource: ezpage.yml }
    - { resource: image.yml }

ezpublish:
    system:
        frontend_group:
            user:
                layout: 'NetgenMoreDemoBundle::pagelayout.html.twig'
                login_template: 'NetgenMoreDemoBundle:user:login.html.twig'
        administration_group:
            user:
                layout: 'NetgenMoreAdminUIBundle::pagelayout_login.html.twig'
                login_template: 'NetgenMoreAdminUIBundle:user:login.html.twig'

ez_publish_legacy:
    system:
        frontend_group:
            templating:
                view_layout: 'NetgenMoreDemoBundle::pagelayout_legacy.html.twig'
                module_layout: 'NetgenMoreDemoBundle::pagelayout_module.html.twig'
        administration_group:
            templating:
                view_layout: 'NetgenMoreAdminUIBundle::pagelayout_legacy.html.twig'
                module_layout: 'NetgenMoreAdminUIBundle::pagelayout_module.html.twig'
