imports:
    - { resource: override.yml }
    - { resource: ezpage.yml }
    - { resource: image.yml }

ezpublish:
    system:
        frontend_group:
            user:
                layout: 'NetgenMoreDemoBundle::pagelayout.html.twig'

ez_publish_legacy:
    system:
        frontend_group:
            templating:
                view_layout: 'NetgenMoreDemoBundle::pagelayout_legacy.html.twig'
                module_layout: 'NetgenMoreDemoBundle::pagelayout_module.html.twig'
