ezpublish:
    system:
        frontend_group:
            image_variations:
                ng_responsive_full:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1000] }
                        - { name: strip }
                ng_responsive_half:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [750] }
                        - { name: strip }
                ng_image_full:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1170] }
                        - { name: strip }
                ng_image_line:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [330] }
                        - { name: strip }
                ng_image_embed:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [330] }
                        - { name: strip }
                ng_image_block_item:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [330] }
                        - { name: strip }
                i320:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [320] }
                        - { name: strip }
                i480:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [480] }
                        - { name: strip }
                i770:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [770] }
                        - { name: strip }
                i960:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [960] }
                        - { name: strip }
                i1140:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1140] }
                        - { name: strip }
                i1540:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1540] }
                        - { name: strip }
                medium:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 200] }
                        - { name: strip }
                contentgrid:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [370] }
                        - { name: geometry/crop, params: [370, 160, 0, 0] }
                        - { name: strip }
                opengraph:
                    reference: null
                    filters:
                        - { name: geometry/scale, params: [200, 200] }
                        - { name: strip }
        administration_group:
            image_variations:
                small:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 100] }
                        - { name: strip }
                medium:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 200] }
                        - { name: strip }
                large:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [300, 300] }
                        - { name: strip }
