ezpublish:
    system:
        default:
            image_variations:
                i320:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [320] }
                        - { name: strip }
                i480:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [480] }
                        - { name: strip }
                i770:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [770] }
                        - { name: strip }
                i1140:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1140] }
                        - { name: strip }
                opengraph:
                    reference: original
                    filters:
                        - { name: geometry/scale, params: [600, 315] }
                        - { name: strip }
        administration_group:
            image_variations:
                small:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 100] }
                        - { name: strip }
                medium:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 200] }
                        - { name: strip }
                large:
                    reference: original
                    filters:
                        - { name: geometry/scaledownonly, params: [300, 300] }
                        - { name: strip }
