ezpublish:
    system:
        frontend_group:
            image_variations:
                i320:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [320] }
                        - { name: strip }
                i480:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [480] }
                        - { name: strip }
                i770:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [770] }
                        - { name: strip }
                i1140:
                    reference: original
                    filters:
                        - { name: geometry/scalewidthdownonly, params: [1140] }
                        - { name: strip }
                opengraph:
                    reference: original
                    filters:
                        - { name: geometry/scale, params: [200, 200] }
                        - { name: strip }
