parameters:
    ngmore_legacy.legacy_mapper.configuration.options:
        enabled_legacy_settings:
            - solr
            - ngmore
            - site

        replace_array_values:
            site:
                SiteSettings:
                    SiteList: true
                SiteAccessSettings:
                    AvailableSiteAccessList: true
