netgen_more_legacy:
    enabled_legacy_settings:
        - content.ini
        - ngmore.ini
        - site.ini

    system:
        frontend_group:
            injected_merge_settings:
                site.ini:
                    SiteAccessRules/Rules:
                        - access;disable
                        - module;content/advancedsearch

        default:
            injected_merge_settings:
                site.ini:
                    ExtensionSettings/ActiveExtensions:
                        - ez_netgen_ngmore_demo
                        - nglayouts
                        - ezplatformsearch
                        - ezrichtext
                        - ngadminui
                        - ngsymfonytools
                        - ngmore
                        - ngclasslist
                        - xrowmetadata
                        - bccie
                        - birthday
                        - childrenindexer
                        - parentindexer
                        - hideuntildate
                        - ezclasslists
                        - ezchangeclass
                        - enhancedselection2
                        - ezmultiupload
                        - eztags
                        - ezjscore
                        - ezstarrating
                        - ezgmaplocation
                        - ezdemo
                        - ezoe

            injected_settings:
                content.ini:
                    ClassGroupIDs/Media: 2
                    ClassGroupIDs/Users: 3
                    # Setup class group was deleted long ago, this makes sure
                    # it doesn't mess up custom groups that have its' old ID
                    ClassGroupIDs/Setup: -1

                site.ini:
                    SiteSettings/DefaultAccess: "%ezpublish.siteaccess.default%"
                    SiteSettings/SiteList: "%ezpublish.siteaccess.list%"
                    SiteSettings/RootNodeDepth: "%ngmore.default.legacy.site_settings.root_node_depth%"
                    SiteSettings/SiteURL: "%ngmore.default.site_domain%"
                    SiteSettings/MetaDataArray: "%ngmore.default.site_settings.meta_data%"

                    SiteAccessSettings/AvailableSiteAccessList: "%ezpublish.siteaccess.list%"
                    SiteAccessSettings/RemoveSiteAccessIfDefaultAccess: enabled
                    # The following two parameters need to be "true" and "false" strings
                    # since eZ legacy config uses those, as opposed to booleans
                    SiteAccessSettings/ForceVirtualHost: "true"
                    SiteAccessSettings/CheckValidity: "false"

                    Session/SessionNameHandler: custom
                    UserSettings/LogoutRedirect: /

                    SiteAccessRules/Rules:
                        - access;disable
                        - module;user/register
                        - module;user/activate
                        - module;user/unactivated
                        - module;user/success
                        - module;user/forgotpassword
                        - module;ezinfo/about
                        - module;ezinfo/copyright
                        - module;content/tipafriend
                        - module;settings/edit
                        - module;layout
                        - module;visual
                        - module;shop

                    DesignSettings/DesignLocationCache: enabled

                    MailSettings/Transport: "%mailer_transport%"
                    MailSettings/TransportServer: "%mailer_host%"
                    MailSettings/TransportPort: "%mailer_port%"
                    MailSettings/TransportUser: "%mailer_user%"
                    MailSettings/TransportPassword: "%mailer_password%"
                    MailSettings/AdminEmail: "%ngmore.default.mail.sender_email%"
                    MailSettings/EmailSender: "%ngmore.default.mail.sender_email%"

                ngmore.ini:
                    GoogleMapsSettings/DefaultLatitude: "%ngmore.default.google_maps.latitude%"
                    GoogleMapsSettings/DefaultLongitude: "%ngmore.default.google_maps.longitude%"
                    GoogleMapsSettings/DefaultZoom: "%ngmore.default.google_maps.zoom%"
                    GoogleMapsSettings/DefaultMapType: "%ngmore.default.google_maps.map_type%"
