netgen_open_graph:
    system:
        frontend_group:
            global_handlers:
                - { handler: ngmore/site_name, tag: "og:site_name" }
            content_type_handlers:
                ng_frontpage:
                    - { handler: literal/text, tag: "og:type", params: [website] }
                    - { handler: ngmore/site_name, tag: "og:title" }
                    - { handler: ngmore/site_name, tag: "og:description" }
                    - { handler: literal/url, tag: "og:image", params: ["/bundles/netgenmoredemo/images/opengraph.png"] }
                ng_landing_page:
                    - { handler: literal/text, tag: "og:type", params: [website] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: literal/url, tag: "og:image", params: ["/bundles/netgenmoredemo/images/opengraph.png"] }
                ng_category:
                    - { handler: literal/text, tag: "og:type", params: [website] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezxmltext, tag: "og:description", params: [full_intro] }
                ng_article:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezxmltext, tag: "og:description", params: [full_intro] }
                    - { handler: field_type/ezimage, tag: "og:image", params: [image, i1200] }
                ng_news:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezxmltext, tag: "og:description", params: [full_intro] }
                    - { handler: field_type/ezimage, tag: "og:image", params: [image, i1200] }
                ng_blog_post:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezxmltext, tag: "og:description", params: [full_intro] }
                    - { handler: field_type/ezimage, tag: "og:image", params: [image, i1200] }
                ng_feedback_form:
                    - { handler: literal/text, tag: "og:type", params: [article] }
                    - { handler: field_type/ezstring, tag: "og:title", params: [title] }
                    - { handler: field_type/ezxmltext, tag: "og:description", params: [full_intro] }
                    - { handler: literal/url, tag: "og:image", params: ["/bundles/netgenmoredemo/images/opengraph.png"] }
