netgen_open_graph:
    system:
        frontend_group:
            global_handlers:
                - { handler: literal/text, tag: 'og:site_name', params: [%ngmore.default.site_settings.site_name%] }
            content_type_handlers:
                ng_frontpage:
                    - { handler: literal/text, tag: 'og:type', params: ['website'] }
                    - { handler: literal/text, tag: 'og:title', params: [%ngmore.default.site_settings.site_name%] }
                    - { handler: literal/text, tag: 'og:description', params: [%ngmore.default.site_settings.site_name%] }
                    - { handler: literal/text, tag: 'og:image', params: ['http://%ngmore.default.site_domain%/bundles/netgenmoredemo/images/opengraph_default_image.png'] }
                ng_landing_page:
                    - { handler: literal/text, tag: 'og:type', params: ['website'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: literal/text, tag: 'og:image', params: ['http://%ngmore.default.site_domain%/bundles/netgenmoredemo/images/opengraph_default_image.png'] }
                ng_category_page:
                    - { handler: literal/text, tag: 'og:type', params: ['website'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: literal/text, tag: 'og:image', params: ['http://%ngmore.default.site_domain%/bundles/netgenmoredemo/images/opengraph_default_image.png'] }
                ng_category:
                    - { handler: literal/text, tag: 'og:type', params: ['website'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: field_type/ezimage, tag: 'og:image', params: ['image'] }
                ng_article:
                    - { handler: literal/text, tag: 'og:type', params: ['article'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: field_type/ezimage, tag: 'og:image', params: ['image'] }
                ng_news:
                    - { handler: literal/text, tag: 'og:type', params: ['article'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: field_type/ezimage, tag: 'og:image', params: ['image'] }
                ng_blog_post:
                    - { handler: literal/text, tag: 'og:type', params: ['article'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: field_type/ezimage, tag: 'og:image', params: ['image'] }
                ng_feedback_form:
                    - { handler: literal/text, tag: 'og:type', params: ['article'] }
                    - { handler: field_type/ezstring, tag: 'og:title', params: ['title'] }
                    - { handler: field_type/ezxmltext, tag: 'og:description', params: ['full_intro'] }
                    - { handler: literal/text, tag: 'og:image', params: ['http://%ngmore.default.site_domain%/bundles/netgenmoredemo/images/opengraph_default_image.png'] }
