ezpublish:
    system:
        ngmore_frontend_group:
            block_view:
                PageTitle:
                    template: NetgenMoreDemoBundle:override/block:page_title.html.twig
                    match:
                        Type: PageTitle
                ContentGrid:
                    template: NetgenMoreDemoBundle:override/block:content_grid.html.twig
                    match:
                        Type: ContentGrid
                ContentGridDynamic:
                    template: NetgenMoreDemoBundle:override/block:content_grid_dynamic.html.twig
                    controller: netgen_more.controller.block_view:viewContentGridDynamicBlockById
                    match:
                        Type: ContentGridDynamic

            location_view:
                full:
                    ng_frontpage:
                        template: NetgenMoreDemoBundle:override/full:ng_frontpage.html.twig
                        match:
                            Identifier\ContentType: ng_frontpage
                    ng_category:
                        template: NetgenMoreDemoBundle:override/full:ng_category.html.twig
                        controller: netgen_more.controller.full_view:viewNgCategoryLocation
                        match:
                            Identifier\ContentType: ng_category
                    ng_landing_page:
                        template: NetgenMoreDemoBundle:override/full:ng_landing_page.html.twig
                        controller: netgen_more.controller.full_view:viewNgLandingPageLocation
                        match:
                            Identifier\ContentType: ng_landing_page
                    ng_category_page:
                        template: NetgenMoreDemoBundle:override/full:ng_category_page.html.twig
                        controller: netgen_more.controller.full_view:viewNgCategoryPageLocation
                        match:
                            Identifier\ContentType: ng_category_page
                block_item:
                    block_item:
                        template: NetgenMoreDemoBundle:override/block_item:block_item.html.twig
                        match: ~

            content_view:
                embed:
                    image:
                        template: NetgenMoreDemoBundle:override/embed:image.html.twig
                        match:
                            Identifier\ContentType: image

            field_templates:
                - { template: NetgenMoreBundle::content_fields.html.twig, priority: 4294967295 }
