parameters:
    ngmore.default.pagelayout: "@@NetgenMoreDemo/pagelayout.html.twig"

    ngmore.default.site_settings.site_name: "Netgen More"

    ngmore.default.search.content_types:
        - ng_blog_post
        - ng_article
        - ng_news
        - ng_category
        - ng_feedback_form
        - ng_landing_page
        - ng_video
        - ng_audio
        - file

    netgen_admin_ui.default.legacy_routes: [ez_urlalias, ngmore_content_search]
