parameters:
    ngmore.default.pagelayout: 'NetgenMoreDemoBundle::pagelayout.html.twig'
    ngmore.administration_group.pagelayout: 'NetgenMoreAdminUIBundle::pagelayout.html.twig'
    ngmore.administration_group.content_view.show_invisible_locations: true
    eztags.administration_group.routing.enable_tag_router: false
    ezsettings.administration_group.treemenu.http_cache: false

    ngmore.default.site_settings.site_name: 'NG More'
    ngmore.default.site_settings.meta_data:
        author: 'Netgen'
        description: 'NG More'
        keywords: 'NG More'
