parameters:
    ngmore.default.pagelayout: "@@ezdesign/pagelayout.html.twig"

    ngmore.default.search.content_types:
        - ng_blog_post
        - ng_article
        - ng_news
        - ng_category
        - ng_feedback_form
        - ng_landing_page
        - ng_video
        - ng_audio
        - file

    netgen_admin_ui.default.legacy_routes: [ez_urlalias, ngmore_content_search]

    ngmore.default.lazy_loading.enabled: true
    ngmore.default.lazy_loading.initial_image_alias: 'i30'
