parameters:
    ngmore.default.pagelayout: 'NetgenMoreDemoBundle::pagelayout.html.twig'

    ngmore.default.site_settings.site_name: 'NG More'
    ngmore.default.site_settings.meta_data:
        author: 'Netgen'
        description: 'NG More'
        keywords: 'NG More'
