parameters:
    ngmore.default.pagelayout: "NetgenMoreDemoBundle::pagelayout.html.twig"

    netgen_content_browser.ezpublish.default_item_template: 'NetgenMoreDemoBundle:browser:item.html.twig'
    netgen_content_browser.ezpublish.default_preview_template: 'NetgenMoreDemoBundle:browser:ngcb_preview.html.twig'

    ngmore.default.site_settings.site_name: "Netgen More"
    ngmore.default.site_settings.meta_data:
        author: Netgen
        copyright: Netgen
        description: "Netgen More"
        keywords: "netgen more"

    ngmore.default.search.content_types:
        - ng_blog_post
        - ng_article
        - ng_news
        - ng_category
        - ng_feedback_form
        - ng_landing_page
        - ng_video
        - ng_audio
        - file

    netgen_admin_ui.default.legacy_routes: [ez_urlalias, ngmore_content_search]
