parameters:
    ngmore.default.pagelayout: 'NetgenMoreDemoBundle::pagelayout.html.twig'
    ngmore.default.site_settings.site_name: 'NG More'

    # Disable handling of Legacy Stack fallback error responses through Symfony exceptions
    # for 'ngadminui' siteaccess
    ngmore.ngadminui.content_view.handle_legacy_fallback_error_result: false
