parameters:
    ngmore.default.pagelayout: 'NetgenMoreDemoBundle::pagelayout.html.twig'
    ngmore.default.user_register.template.activation_mail: 'NetgenMoreDemoBundle:user/mail:activation_mail.html.twig'
    ngmore.default.user_register.template.register: 'NetgenMoreDemoBundle:user:register.html.twig'
    ngmore.default.user_register.template.activate: 'NetgenMoreDemoBundle:user:activate.html.twig'
    ngmore.default.user_register.template.forgotten_password: 'NetgenMoreDemoBundle:user:forgotten_password.html.twig'
    ngmore.default.user_register.template.forgotten_password_mail: 'NetgenMoreDemoBundle:user/mail:forgotten_password.html.twig'
    ngmore.default.user_register.template.reset_password: 'NetgenMoreDemoBundle:user:reset_password.html.twig'
    ngmore.default.user_register.mail_sender: 'info@netgen.hr'
    ngmore.default.user_register.user_group: 11
    ngmore.default.user_register.auto_enable: false
