parameters:
    ngmore.default.pagelayout: 'NetgenMoreDemoBundle::pagelayout.html.twig'

    ngmore.default.user_register.template.register: 'NetgenMoreDemoBundle:user:register.html.twig'
    ngmore.default.user_register.template.register_success: 'NetgenMoreDemoBundle:user:register_success.html.twig'

    ngmore.default.user_register.template.activate: 'NetgenMoreDemoBundle:user:activate.html.twig'
    ngmore.default.user_register.template.activate_done: 'NetgenMoreDemoBundle:user:activate_done.html.twig'
    ngmore.default.user_register.template.activate_sent: 'NetgenMoreDemoBundle:user:activate_sent.html.twig'

    ngmore.default.user_register.template.forgotpassword: 'NetgenMoreDemoBundle:user:forgot_password.html.twig'
    ngmore.default.user_register.template.forgotpassword_sent: 'NetgenMoreDemoBundle:user:forgot_password_sent.html.twig'
    ngmore.default.user_register.template.resetpassword: 'NetgenMoreDemoBundle:user:reset_password.html.twig'
    ngmore.default.user_register.template.resetpassword_done: 'NetgenMoreDemoBundle:user:reset_password_done.html.twig'

    ngmore.default.user_register.template.mail.welcome: 'NetgenMoreDemoBundle:user/mail:welcome_mail.html.twig'
    ngmore.default.user_register.template.mail.activation: 'NetgenMoreDemoBundle:user/mail:activation_mail.html.twig'
    ngmore.default.user_register.template.mail.forgotten_password: 'NetgenMoreDemoBundle:user/mail:forgotten_password.html.twig'
    ngmore.default.user_register.template.mail.email_not_registered: 'NetgenMoreDemoBundle:user/mail:not_registered_mail.html.twig'
    ngmore.default.user_register.template.mail.password_changed: 'NetgenMoreDemoBundle:user/mail:password_changed.html.twig'
    ngmore.default.user_register.template.mail.activation_mail_not_registered: 'NetgenMoreDemoBundle:user/mail:activation_mail_not_registered.html.twig'
    ngmore.default.user_register.template.mail.user_already_active: 'NetgenMoreDemoBundle:user/mail:user_already_active.html.twig'
    ngmore.default.user_register.template.mail.user_disabled: 'NetgenMoreDemoBundle:user/mail:user_disabled.html.twig'
    ngmore.default.user_register.template.mail.user_not_activated: 'NetgenMoreDemoBundle:user/mail:user_not_activated.html.twig'
