parameters:
    ngmore.default.template.user.activate: "@@NetgenMoreDemo/user/activate.html.twig"
    ngmore.default.template.user.activate_done: "@@NetgenMoreDemo/user/activate_done.html.twig"
    ngmore.default.template.user.activate_sent: "@@NetgenMoreDemo/user/activate_sent.html.twig"
    ngmore.default.template.user.activate_admin_activation_pending: "@@NetgenMoreDemo/user/activate_admin_activation_pending.html.twig"

    ngmore.default.template.user.forgot_password: "@@NetgenMoreDemo/user/forgot_password.html.twig"
    ngmore.default.template.user.forgot_password_sent: "@@NetgenMoreDemo/user/forgot_password_sent.html.twig"

    ngmore.default.template.user.register: "@@NetgenMoreDemo/user/register.html.twig"
    ngmore.default.template.user.register_success: "@@NetgenMoreDemo/user/register_success.html.twig"

    ngmore.default.template.user.reset_password: "@@NetgenMoreDemo/user/reset_password.html.twig"
    ngmore.default.template.user.reset_password_done: "@@NetgenMoreDemo/user/reset_password_done.html.twig"

    ngmore.default.template.user.mail.activate: "@@NetgenMoreDemo/user/mail/activate.html.twig"
    ngmore.default.template.user.mail.activate_already_active: "@@NetgenMoreDemo/user/mail/activate_already_active.html.twig"
    ngmore.default.template.user.mail.activate_disabled: "@@NetgenMoreDemo/user/mail/activate_disabled.html.twig"
    ngmore.default.template.user.mail.activate_not_registered: "@@NetgenMoreDemo/user/mail/activate_not_registered.html.twig"
    ngmore.default.template.user.mail.activate_admin_activation_pending: "@@NetgenMoreDemo/user/mail/activate_admin_activation_pending.html.twig"
    ngmore.default.template.user.mail.activate_admin_activation_required: "@@NetgenMoreDemo/user/mail/activate_admin_activation_required.html.twig"

    ngmore.default.template.user.mail.forgot_password: "@@NetgenMoreDemo/user/mail/forgot_password.html.twig"
    ngmore.default.template.user.mail.forgot_password_disabled: "@@NetgenMoreDemo/user/mail/forgot_password_disabled.html.twig"
    ngmore.default.template.user.mail.forgot_password_not_active: "@@NetgenMoreDemo/user/mail/forgot_password_not_active.html.twig"
    ngmore.default.template.user.mail.forgot_password_not_registered: "@@NetgenMoreDemo/user/mail/forgot_password_not_registered.html.twig"
    ngmore.default.template.user.mail.forgot_password_password_changed: "@@NetgenMoreDemo/user/mail/forgot_password_password_changed.html.twig"

    ngmore.default.template.user.mail.welcome: "@@NetgenMoreDemo/user/mail/welcome.html.twig"

    ngmore.default.template.errors.403: "@@NetgenMoreDemo/errors/403.html.twig"
    ngmore.default.template.errors.404: "@@NetgenMoreDemo/errors/404.html.twig"
    ngmore.default.template.errors.500: "@@NetgenMoreDemo/errors/500.html.twig"
    ngmore.default.template.errors.default: "@@NetgenMoreDemo/errors/default.html.twig"

    ngmore.default.template.search: "@@NetgenMoreDemo/search/search.html.twig"
