imports:
    # Keep ezplatform.yml before config.yml
    - { resource: ezplatform.yml }
    - { resource: ../dev/config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/behat/routing.yml"
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: false
